x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: JABA_SUPER_USER_MINIO
    MINIO_ROOT_PASSWORD: jaba127!368601NO
  healthcheck:
    test: [ "CMD", "mc", "ready", "local" ]
    interval: 5s
    timeout: 5s
    retries: 5

x-neo4j-common: &neo4j-common
  image: neo4j:4.4-enterprise
  environment:
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

    - NEO4J_dbms_mode=CORE
    - NEO4J_causal_clustering_discovery_type=LIST
    - NEO4J_causal_clustering_initial_discovery_members=neo4j1:5000,neo4j2:5000,neo4j3:5000
  expose:
    - "5000"
  networks:
    - workshop

services:
  couchbase-server:
    build: configs/couchbase/couchbase-server
    ports:
      - 8091-8096:8091-8096
      - 11210:11210
    environment:
      - CLUSTER_NAME=couchbase-demo
      - COUCHBASE_ADMINISTRATOR_USERNAME=jaba_admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=jaba_pwd
      - COUCHBASE_BUCKET=doom-scrolling
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=jaba_rbac
      - COUCHBASE_RBAC_PASSWORD=jaba_rbac_pwd
      - COUCHBASE_RBAC_NAME=jaba_rbac_name
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    hostname: couchbase-server
    container_name: couchbase-server
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - workshop
    entrypoint: ['']
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"
  neo4j1:
    <<: *neo4j-common
    container_name: neo4j1
    hostname: neo4j1
    environment:
      - NEO4J_dbms__default__advertised__address=neo4j1
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j1-data:/data
      - neo4j1-logs:/logs

  neo4j2:
      <<: *neo4j-common
      container_name: neo4j2
      hostname: neo4j2
      environment:
        - NEO4J_dbms__default__advertised__address=neo4j2
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_AUTH=neo4j/password123
      ports:
        - "8484:7474"
        - "8687:7687"
      volumes:
        - neo4j2-data:/data
        - neo4j2-logs:/logs

  neo4j3:
      <<: *neo4j-common
      container_name: neo4j3
      hostname: neo4j3
      environment:
        - NEO4J_dbms__default__advertised__address=neo4j3
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_AUTH=neo4j/password123
      ports:
        - "9494:7474"
        - "9687:7687"
      volumes:
        - neo4j3-data:/data
        - neo4j3-logs:/logs
#  neo4j1:
#    <<: *neo4j-common
#    container_name: neo4j1
#    hostname: neo4j1
#    ports:
#      - "7474:7474"   # HTTP
#      - "7687:7687"   # Bolt
##      - "5000:5000"   # discovery
#
#  neo4j2:
#      <<: *neo4j-common
#      container_name: neo4j2
#      hostname: neo4j2
#      ports:
#        - "8484:7474"
#        - "8687:7687"
##        - "5000:5000"
#
#  neo4j3:
#      <<: *neo4j-common
#      container_name: neo4j3
#      hostname: neo4j3
#      ports:
#        - "9494:7474"
#        - "9687:7687"
##        - "5000:5000"
#  neo4j:
#    container_name: neo4j
#    image: neo4j:latest
#    ports:
#      - 7474:7474
#      - 7687:7687
#    environment:
#      - NEO4J_AUTH=neo4j/password123

  clickhouse:
    image: 'clickhouse/clickhouse-server:23.4'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9005:9000'
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: 'clickhouse/clickhouse-keeper:23.4-alpine'
    user: '101:101'
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    ports:
      - '127.0.0.1:9181:9181'

  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '0YVmO2e179ymcr4AZoA9FOEAIZSdDmezA8yIuLnSL4ERowgKZGKWEKqZAR64BCVn1aC4tN6Jq7aVM0ldAMZJIQ=='
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

secrets:
  influxdb2-admin-username:
    file: configs/influx-secrets/influxdb2-admin-username
  influxdb2-admin-password:
    file: configs/influx-secrets/influxdb2-admin-password
  influxdb2-admin-token:
    file: configs/influx-secrets/influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config:
  dgraph:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  neo4j1-data:
  neo4j2-data:
  neo4j3-data:
  neo4j1-logs:
  neo4j2-logs:
  neo4j3-logs:

networks:
  workshop:
    driver: bridge
